version: '3.4'

services:
  luxclusif.aggregator.webapi:
    image: ${DOCKER_REGISTRY-}luxclusifaggregatorwebapi
    build:
      context: .
      dockerfile: luxclusif.aggregator.webapi/Dockerfile
    networks: 
    - luxclusif-aggregator-network 

  luxclusif-aggregator-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
      POSTGRES_DB: "luxclusif.aggregator"
    networks:
      - luxclusif-aggregator-network
    volumes:
      - ./Local/pgdata:/var/lib/postgresql/data

  luxclusif-aggregator-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@luxclusif.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    volumes:
      - ./Local/pgadmin/pgadmin:/var/lib/pgadmin \
      - ./Local/pgadmin/certs/certificate.cert:/certs/server.cert \
      - ./Local/pgadmin/certs/certificate.key:/certs/server.key \
      - ./Local/pgadmin/tmp/servers.json:/pgadmin4/servers.json
    networks:
      - luxclusif-aggregator-network
    depends_on:
      - luxclusif-aggregator-postgres

  luxclusif-aggregator-schema:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.conf -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./Local/database/dev-data:/flyway/sql
      - ./Local/drivers:/flyway/drivers
      - ./Local/database/conf:/flyway/conf
    depends_on:
      - luxclusif-aggregator-postgres
    networks:
      - luxclusif-aggregator-network

  luxclusif-aggregator-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./Local/rabbitmq/data/:/var/lib/rabbitmq/
        - ./Local/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - luxclusif-aggregator-network

networks:
  luxclusif-aggregator-network:
    driver: bridge